out1  <- readRDS(file = "_outputs/out1.RData")
out2  <- readRDS(file = "_outputs/out2.RData")
out3  <- readRDS(file = "_outputs/out3.RData")
out4  <- readRDS(file = "_outputs/out4.RData")
out5  <- readRDS(file = "_outputs/out5.RData")
out6  <- readRDS(file = "_outputs/out6.RData")
out7  <- readRDS(file = "_outputs/out7.RData")
out8  <- readRDS(file = "_outputs/out8.RData")
out9  <- readRDS(file = "_outputs/out9.RData")
out10 <- readRDS(file = "_outputs/out10.RData")
out11 <- readRDS(file = "_outputs/out11.RData")
out12 <- readRDS(file = "_outputs/out12.RData")
out13 <- readRDS(file = "_outputs/out13.RData")
out14 <- readRDS(file = "_outputs/out14.RData")


# cohwT(-2,5)
out6_wide  <- readRDS(file = "_outputs/out6_wide.RData")
out7_wide  <- readRDS(file = "_outputs/out7_wide.RData")
out8_wide  <- readRDS(file = "_outputs/out8_wide.RData")
out9_wide  <- readRDS(file = "_outputs/out9_wide.RData")