source("_scripts/_simulate_model.r")

out1  <- simulate_model("RevLearn_RL",1)
out2  <- simulate_model("RevLearn_RLnc",1)
out3  <- simulate_model("RevLearn_RLnc_2lr",1)
out4  <- simulate_model("RevLearn_RLnc_cfa",1)
out5  <- simulate_model("RevLearn_RLnc_2lr_cfa",1)
out6  <- simulate_model("RevLearn_RLcoh",1)
out7  <- simulate_model("RevLearn_RLcoh_2lr",1)
out8  <- simulate_model("RevLearn_RLcoh_cfa",1)
out9  <- simulate_model("RevLearn_RLcoh_2lr_cfa",1)
out10 <- simulate_model("RevLearn_RLcoh_2lr_bet",1)
out11 <- simulate_model("RevLearn_RLcumrew",1)
out12 <- simulate_model("RevLearn_RLcumrew_cfa",1)
out13 <- simulate_model("RevLearn_RLcumrew_2lr",1)
out14 <- simulate_model("RevLearn_RLcumrew_2lr_cfa",1)

# save(lst1, lst2, lst3,  file = '_outputs/jags_output.Rdata')

saveRDS(out1,file ="_outputs/out1.RData",compress=F)
saveRDS(out2,file ="_outputs/out2.RData",compress=F)
saveRDS(out3,file ="_outputs/out3.RData",compress=F)
saveRDS(out4,file ="_outputs/out4.RData",compress=F)
saveRDS(out5,file ="_outputs/out5.RData",compress=F)
saveRDS(out6,file ="_outputs/out6.RData",compress=F)
saveRDS(out7,file ="_outputs/out7.RData",compress=F)
saveRDS(out8,file ="_outputs/out8.RData",compress=F)
saveRDS(out9,file ="_outputs/out9.RData",compress=F)
saveRDS(out10,file="_outputs/out10.RData",compress=F)
saveRDS(out11,file="_outputs/out11.RData",compress=F)
saveRDS(out12,file="_outputs/out12.RData",compress=F)
saveRDS(out13,file="_outputs/out13.RData",compress=F)
saveRDS(out14,file="_outputs/out14.RData",compress=F)
